name: Release

env:
  CI: true

on:
  push:
    tags:
      - v*

# https://github.com/actions/create-release#example-workflow---create-a-release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - env:
          # DO NOT use ${{ secrets.GITHUB_TOKEN }}, since it will not trigger
          # events, like the `release` event, and downstream workflows will
          # not run.
          # See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          GITHUB_TOKEN: ${{ secrets.BOT_ACTIONS_RELEASE }}
        uses: actions/create-release@v1
        with:
          draft: true
          prerelease: true
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
